name: ml-2018
channels:
- conda-forge
dependencies:
  - python=3.6.3
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - pandas
  - jupyter
  - jupyterlab
  - notebook
  - pytorch -c pytorch
  - torchvision -c pytorch
