name: ml-2018
channels:
- conda-forge
- pytorch
dependencies:
  - python=3.6.3
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - pandas
  - jupyter
  - jupyterlab
  - notebook
  - pytorch
  - torchvision
